### PR TITLE
Make `eslint` spark joy

### PR DESCRIPTION
**Pull request by erxclau**
#### What's this PR do?

- Removes Airbnb linting rules.
- Adds a recommended extensions file for VSCode.
- Adds a settings file for VSCode.

#### Are there any relevant screenshots?

N/A

#### Why are we doing this? How does it help us?

<https://twitter.com/dan_abramov/status/1086215004808978434?lang=en>

#### How should this be manually tested?

N/A

#### Are there any smells or added technical debt to note?

N/A

#### What are relevant issues or links?

N/A

#### Have you done the following, if applicable:

* [x] Performed a self-review of the code?
* [x] Linted code for good style and standards?
* [ ] Added unit tests?
* [ ] Tested manually on mobile?
* [ ] Checked for performance implications?
* [ ] Checked accessibility?
* [ ] Checked for vulnerabilities with `yarn audit --level=high`?
* [ ] Updated any documentation

### CODE REVIEW

**Comment by mattbilik** [comment]
Looks good! Went through some examples – I think this is much better than the full Airbnb guide, but I still think that we need to keep some of Airbnb's ES6 rules. Here are a few that I think are relevant:
1. [https://github.com/airbnb/javascript#arrow-functions](https://github.com/airbnb/javascript#arrow-functions)
2. prefer-const in addition to no-var
3. https://github.com/airbnb/javascript#es6-template-literals

**Comment by erxclau** [comment]
Just leaving a note here that even though we have `eqeqeq: "error"` in the config, that doesn't mean we should necessarily always use `===`. There are some cases where loose equality comparison [may be desirable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness). 

The point of this config is to make you really consider if you want to do something. If necessary, just disable it with a comment. We can also change this to a `warn`.

**Comment by erxclau** [comment]
> prefer-const in addition to no-var

I think I want this too. I didn't include it because I hadn't (and still haven't) come up with a good opinion about the [destructuring](https://eslint.org/docs/latest/rules/prefer-const#destructuring) rules. I remember getting annoyed by the `any` default before.

**Comment by erxclau** [comment]
@mattbilik Added those three rules. I was hesitant about preferring arrow functions but it seems that `eslint` will recognize when the `this` keyword is being used such that it'll allow the `function` notation.

**Pull request merged**
