### PR TITLE
Add button for client-side image download

### PR DESCRIPTION
**Pull request by erxclau**
#### What's this PR do?

Adds a button that allows people to download the graphic as a PNG.

This works by listening for a button click. When the button is clicked, the Pym parent sends a message to the Pym child. The Pym child then generates the PNG. The Pym parent can't directly generate the PNG because `html-to-image` can't seem to find the correct styles from the parent.

#### Are there any relevant screenshots?

N/A

#### Why are we doing this? How does it help us?

See #8.

#### How should this be manually tested?

1. Clone and checkout to this branch.
2. Spin up your server.
3. Click the button.
4. Try resizing your iframe width.
5. Try adding some SVG content

```javascript
const data = new Map()
    .set("A", 4)
    .set("B", 2)
    .set("C", 9)
    .set("D", 5)
    .set("E", 8);

  const figure = d3.select("figure");
  const width = figure.node().clientWidth;
  const height = 300;
  const margin = { left: 50, top: 20, right: 20, bottom: 20 };

  const x = d3
    .scaleLinear()
    .domain([0, d3.max(data.values())])
    .range([margin.left, width - margin.right]);

  const y = d3
    .scaleBand()
    .domain(data.keys())
    .range([margin.top, height - margin.bottom])
    .padding(0.3);

  const svg = figure.append("svg").attr("width", width).attr("height", height);

  svg
    .append("g")
    .attr("transform", `translate(${margin.left}, 0)`)
    .call(d3.axisLeft(y));

  svg
    .append("g")
    .attr("transform", `translate(0, ${margin.top})`)
    .call(d3.axisTop(x));

  svg
    .selectAll("rect")
    .data(data.entries())
    .join("rect")
    .attr("y", (d) => y(d[0]))
    .attr("height", y.bandwidth())
    .attr("x", x(0))
    .attr("width", (d) => x(d[1]) - x(0))
    .attr("fill", "steelblue");
```

#### Are there any smells or added technical debt to note?

No

#### What are relevant issues or links?

#8 

#### Have you done the following, if applicable:

* [x] Performed a self-review of the code?
* [x] Linted code for good style and standards?
* [ ] Added unit tests?
* [ ] Tested manually on mobile?
* [x] Checked for performance implications?
* [ ] Checked accessibility?
* [ ] Checked for vulnerabilities with `yarn audit --level=high`?
* [ ] Updated any documentation

### CODE REVIEW

**Comment by erxclau** [comment]
I didn't choose SVG as the image format here because the SVG was huge (like 4MB for the bar chart). But, it'd probably be useful to be able to export an SVG if someone wants to do something with it in Illustrator. Maybe we can allow both PNG and SVG? Options? Two buttons?

**Comment by naitian** [comment]
Ok so this walks back on the original issue a little, but related to the SVG thing.

One concern I have about this button is that, often, the web graphic isn't what we want to use for the social graphic (it's usually too detailed, the hed/dek are too small, etc. I'm worried these will be used for social graphics when in reality it's probably more useful as a preview for developers, or as a quick thumbnail reference.

When I made social graphics manually, I'd download the SVG and tweak it in illustrator first. So in this PR, maybe adding SVG as an option is useful.

Looking forward, maybe (strong emphasis on maybe -- I'm not convinced this is a good idea) there should be support for a "social" version of the graphic, and only allow PNG downloads of that.

**Comment by erxclau** [comment]
Yea, will definitely add an SVG option, even outside the scope of social images but for any ai2html flow that might start with D3 first.

**Comment by erxclau** [comment]
The image currently captures all the text surrounding the figure by the way, which may be desirable in some situations but maybe not in others.

**Comment by erxclau** [comment]
> Looking forward, maybe (strong emphasis on maybe -- I'm not convinced this is a good idea) there should be support for a "social" version of the graphic, and only allow PNG downloads of that.

This could be interesting. We can probably change the font and text font pretty easily just for whenever a screen grab is occurring. But reducing graphic detail might be more complicated.

**Comment by erxclau** [comment]
I don't think this is tree shaking properly but whatever. 

I think this PR is ready to merge for now, unlinking it from #8 so that issue doesn't get closed yet.

**Review by mattbilik — APPROVED** [review]
Tested – looks good to me! I don't image that we'll need to support more formats, but for animated visuals it might be a good idea to add something like this (<https://www.npmjs.com/package/html-to-gif>) also

**Pull request merged**
